export const WEBSITE_BASE_URL = 'http://localhost:4000'
export const PRODUCTS_BASEURL = 'http://localhost:4000/products'
export const ORDERS_BASEURL = 'http://localhost:4000/orders'
export const SHIPPING_BASEURL = 'http://localhost:4000/shipping'
export const NOTIFICATIONS_BASEURL = 'http://localhost:4000/notifications'
export const PAYMENTS_BASEURL = 'http://localhost:4000/payments'
export const USER_BASEURL = 'http://localhost:4000/users'